version: "3.8"
services:
  odoo-db:
    image: postgres:15
    shm_size: "2gb"
    container_name: odoo-db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: odoo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m
      timeout: 5s
      retries: 3

  odoo-web:
    build:
      context: .
      dockerfile: Dockerfile.odoo
    container_name: odoo-web
    restart: always
    volumes:
      - ./data/odoo:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    depends_on:
      - odoo-db
    # ports:
    #   - 8069:8069
    #   - 8072:8072
    environment:
      - HOST=odoo-db
      - PORT=5432
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069/"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m

  odoo-proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: odoo-proxy
    restart: always
    volumes:
      - ./le:/etc/letsencrypt
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - odoo-web
    ports:
      # - "${IP:-0.0.0.0}:80:80"
      - "${IP:-0.0.0.0}:443:443"
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 1m
