from . import ks_woo_price_list
from . import ks_woo_connector_instance
from . import ks_woo_logs
from . import ks_account_tax
from . import ks_woo_attribute
from . import ks_woo_attribute_values
from . import ks_woo_product_template
from . import ks_woo_product_tag
from . import ks_woo_product_category
from . import ks_woo_payment_gateway
from . import ks_woo_product_variants
from . import ks_woo_product_images
from . import ks_woo_res_partner
from . import ks_res_partners
from . import ks_woo_coupon
from . import ks_woo_sale_order
from . import ks_woo_auto_sale_workflow_configuration
from . import ks_email_report
from . import ks_account_move
from . import dashboard
from . import ks_webhook_configuration
from . import ks_global_record_mapping
from . import ks_woo_sales_reporting
from . import ks_woo_meta_mapping
from . import ks_woo_webhook_logs
from . import ks_reverse_workflow
from . import ks_woo_shipping_methods
from . import ks_woo_auto_product_sync
from . import ks_woo_customer_sync
