name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:

  deploy:
    name: Addons
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout    
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Adding Known Hosts
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{ vars.EC2_HOST }} >> ~/.ssh/known_hosts  

      - name: Deploy
        run: |
          echo "${{ secrets.AWS_PEM_KEY }}" | tr -d '\r' > PEMKEYFILE.pem
          chmod 400 PEMKEYFILE.pem
          rsync -rae "ssh -i ./PEMKEYFILE.pem" addons/* ubuntu@${{ vars.EC2_HOST }}:~/odoo/odoo-alfalab/addons
          ssh -i ./PEMKEYFILE.pem ubuntu@${{ vars.EC2_HOST }} 'docker restart odoo-web-al'
